gomorpheus/terraform-provider-morpheus

- docs/guides/getting_started.md
When using PowerShell in Windows, the environment variables are referenced differently than CMD.
Added a few other grammar items.
> Updated documentation

- .github/workflows/release.yml
This PR updates the Github action utilized to sign releases due to a breaking change in the existing Github action. The Github action is recommended by HashiCorp as a replacement (https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410).
> Update CI release automation

- CHANGELOG.md
- morpheus/resource_ansible_integration.go
This PR fixes the issue with properly setting the default branch for the Ansible integration resource.
> Fix the default branch for the ansible integration resource

- morpheus/diff_suppress_funcs.go
- morpheus/resource_manual_option_list.go
- morpheus/util.go
In the resource_manual_option_list, JSON whitespace shows up as changes. I've implemented the diff suppress function capability for the dataset so it ignores whitespace. This code came from https://github.com/huaweicloud/terraform-provider-huaweicloudstack.
> Suppress JSON whitespace changes

- morpheus/resource_backup_setting.go
The currently implementation of morpheus_backup_setting does not work if a storage bucket and default schedule are not provided. This change only sends defaultStorageBucket.id and defaultSchedule.id to the API if they're != 0.
> backup_setting - Only apply storage bucket and schedule if applicable

- morpheus/resource_rest_option_list.go
Attempt to fix #105 
The `source_headers` is also not working, but I guess that's due to the fact that `masked` is unsupported.
> Fix `null` value on `source_url` and `source_method` on tf import

- morpheus/resource_shell_script_task.go
When operating with shell script tasks the following fields were missing
- taskOptions.localScriptGitId
- taskOptions.localScriptGitRef
- visibility
This pull request is dependent on gomorpheus/morpheus-go-sdk#73
> Added missing fields to script tasks

- docs/resources/aws_cloud.md
- morpheus/resource_aws_cloud.go
Added support for an optional `role_arn` attribute on the `aws_cloud` resource for specifying the AWS IAM role Morpheus should assume with STS for a cloud. 
Not much code was needed, but this is my first time working with go, so please pay extra heed in your review.
I ran integration tests locally with success.
Resolves #103
> Add assume role support to AWS cloud

- docs/data-sources/resource_pool.md
- docs/resources/vsphere_instance.md
- morpheus/data_source_resource_pool.go
`id` was missing from the `morpheus\data_source_resource_pool.go` but included in documentation. 
Changes: 
- Added ID as argument
- Changed ID from string to number to match existing patterns
- Adjusted Error message when either ID or name is not provided
I would also note though that the implementation I found in `data_source_cloud.go` to be better. Currently, giving both name and ID will return a positive 200 with the information, so it is not broken. I would say though for consistency, I would go with `data_source_cloud.go` implementation. 
From `data_source_cloud.go`
```golang
Schema: map[string]*schema.Schema{
"id": {
Type:          schema.TypeInt,
Optional:      true,
ConflictsWith: []string{"name"},
Computed:      true,
},
"name": {
Type:          schema.TypeString,
Description: …
```
> `data_source_resource_pool.go` update to include ID

- docs/resources/file_template.md
- docs/resources/script_template.md
- examples/resources/morpheus_file_template/resource.tf
- examples/resources/morpheus_script_template/resource.tf
- morpheus/resource_file_template.go
- morpheus/resource_script_template.go
The SDK supports labels on these resources, so this pull request implements them on the terraform provider scrip template and file template resources.
I noted instance type, instance layout and node type do not have labels support in the provider either, but the SDK will need some modification before they can be added so will address that in separate PRs.
> Adds labels support to script template and file template

- morpheus/resource_app_blueprint_catalog_item.go
This is not perfect, but it stops the flip flopping of the custom icon and resource.svg. In my testing it is not possible to remove the icons via TF without deleting and recreating the resource, but then I don't think the code in master supports this either, as no changes are detected when removing or setting the fields to their nil values.
> improves image handling fixes #182

- go.mod
- go.sum
- morpheus/config.go
Allow developers to "see" what the provider is sending over the wire
in terms of morpheus API calls.
For this to work you need to set both:
```
export TF_LOG=DEBUG (or TF_LOG=TRACE)
export MORPHEUS_API_HTTPTRACE=true
```
We require `MORPHEUS_API_HTTPTRACE` in addition to the TF_LOG variable so that
http tracing (which may contain sensitive information) is not enabled when standard
terraform debugging is enabled.
> Allow tracing of http requests/responses

- docs/resources/vsphere_mks_cluster.md
- examples/resources/morpheus_vsphere_mks_cluster/resource.tf
- morpheus/resource_vsphere_mks_cluster.go
This PR contains a number of changes which ultimately allow for a user to add or remove worker nodes using the Terraform provider with an MKS VSphere cluster.
Updating the `count` value of the `worker_node_pool` field will perform scaling up/down of the number of worker nodes.
The cluster must have a minimum of 3 worker nodes, which is also the default value if `count` is not specified.
Documentation around these changes has also been updated.
PCCP-156
PCCP-157
PCCP-179
> Implement cluster worker node count update for MKS VSphere

- go.sum
The go.sum file seemed to have the wrong version of the Go SDK. This just runs `go mod tidy` to fix the import.
> Run go mod tidy to fix go sdk import

- morpheus/resource_vsphere_instance.go
A couple of customers have reported stack-traces from morpheus_vsphere_instance.  The reason for these stack-traces is that GETs of specific resources return 403s, but instead of returning with an error the code continues to execute and will eventually try to access a field that is nil.  To fix this we make two sets of changes:
- return if there is a GET error
- check the return code of various casts, and if not ok then return with an error
> Return on error in morpheus_vsphere_instance

- docs/resources/vsphere_instance.md
- morpheus/resource_vsphere_instance.go
Some customers want to use terraform to provision instances using sub-tenant users who may not have sufficient privilege to GET information on instance-types in the master tenant.  To accommodate this use-case we've added "instance_type_code" to the Schema of morpheus_vsphere_instance.  This will bypass the logic in morpheus_vsphere_instance to GET instance-type information and retrieve the code from it.  We're using "ExactlyOneOf" in the Schema to make sure that only one of "instance_type_code" or "instance_type_id" are specified when creating a morpheus_vsphere_instance, and that one of them is always specified.
> Add instance_type_code to morpheus_vsphere_instance

- docs/resources/vsphere_instance.md
- morpheus/resource_vsphere_instance.go
Some customers want to get the IP address of a created instance for use as inventory for Ansible (for example).  The API spec includes a "connection_info" list which from testing is populated with the IP address and port to be used in connecting to a network interface.  In this PR we add "connection_info" to the Schema for morpheus_vsphere_instance and populate it with values from the reponse to the POST request.
We also add the interface information returned from the POST to the state-file.
> Add connection_info to morpheus_vsphere_instance

- docs/resources/vsphere_instance.md
- morpheus/resource_vsphere_instance.go
In this PR we make the morpheus_vsphere_instance connection_info read-only - i.e. it cannot be set by the user.
> Make morpheus_vsphere_instance connection_info read-only

- docs/resources/vsphere_instance.md
- go.mod
- morpheus/resource_vsphere_instance.go
There are a few changes to morpheus_vsphere_instance in this PR:
- we add a new "volumes" attribute - datastore_auto_selection - which is a string with two possible values, "auto" and "autoCluster"
- this new attribute can only be set when datastore_id is not set
- to enforce the above we've had to write a CustomizeDiff function called volumesCustomizeDiff since the standard "conflicts_with" doesn't work for lists or sets
- while testing we noticed that a new instance creation was being triggered if "instance_type_code" wasn't set in the resource block
- to fix this we:
- removed "ForceNew" from "instance_type_code" and "instance_type_id"
- this means that a change will trigger an update, which will be a no-op since the update logic doesn't handle changes
- to check for actual changes to …
> Allow automatic selection of Datastore (and other changes)

- morpheus/resource_vsphere_instance.go
We introduced a bug in v0.13.1 whereby we only allowed the user to set one of instance_type_code or instance_type_id in the config for morpheus_vsphere_instance but we stored the value of both in the state-file.  To fix this in this PR we:
- add logic to morpheus_vsphere_instance to only set the value of instance_type_code in the state-file if there is a change
- add logic to do the same with instance_type_id The logic is added to the read method.
This code will repair the bug in existing state-files and ensure that the bug will not reoccur.  This means that on the first run of apply with where a morpheus_vsphere_instance is present in the state-file an update will be performed which won't change the instance but which will fix the state-file (on the read).  Subsequent runs of apply will …
> Only set one of instance_type_code or instance_type_id in state-file

- morpheus/resource_vsphere_instance.go
We were incorrectly asserting that instance_type_id as specified by the user is int64.  It is actually int.
> Fix int64 bug in morpheus_vsphere_instance
